# Generated by Django 4.0.1 on 2022-02-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_book_chapter_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='chapter',
            new_name='chapter_index',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='exercise_index',
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
