# Generated by Django 4.0.1 on 2022-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_book_exercise_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='book',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.IntegerField(),
        ),
    ]
