# Generated by Django 4.0.1 on 2022-02-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_chapter_book_alter_topic_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='chapter_index',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_index',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='topic_index',
            new_name='topic',
        ),
    ]
