# Generated by Django 4.0.1 on 2022-02-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_rename_book_id_exercise_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='index',
            new_name='exercise_nr',
        ),
    ]
