# Generated by Django 4.0.1 on 2022-02-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_chapter_book_alter_topic_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='book',
            new_name='book_id',
        ),
    ]
