# Generated by Django 4.0.1 on 2022-02-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_chapter_book_id_remove_topic_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='book',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.book'),
            preserve_default=False,
        ),
    ]
