# Generated by Django 4.0.1 on 2022-02-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_rename_book_id_chapter_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='book',
            new_name='book_id',
        ),
    ]
